---
title: "DATA467_project"
output: pdf_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(data.table)
library(glmnet)
library(rsample)
library(leaps)
```

```{r}
df = readRDS('D:\\R\\data_467\\data467_project\\GSE39612_edat.RDS')
df2 <- data.frame(t(df))
row_names = row.names(df2)
df2$Patient = row_names
rownames(df2) = NULL

y = read.csv('D:\\R\\data_467\\data467_project\\patient_data.csv', header = FALSE, col.names = c('Patient','Tumor_type', 'Sample_type', 'Sample_name'))
y$Tumor_type = gsub(',','', y$Tumor_type)
y$Sample_type = gsub(',','', y$Sample_type)
y$Sample_name = gsub(',','', y$Sample_name)

merged_df = merge(df2,y, by = 'Patient')
numerical_df = merged_df[,1:20184]
numerical_df$sick = rep(1,length(numerical_df$Patient))
numerical_df$Patient = NULL
categorical_df = merged_df[,c(1,20185,20186,20187)]
merged_df; numerical_df; categorical_df
```
```{r, numerical}
x = regsubsets(x = sick ~., data - numerical_df, method = 'exhaustive', nvmax = 8)
x = summary(x)
x
# numerical_split = initial_split(numerical_df, prop = 0.7)
# num_train = training(numerical_split)
# num_train_y = num_train$Patient
# num_train_x = lm(Patient ~. , data = num_train)
# 
# num_test = testing(numerical_split)
# num_test_y = num_test$Patient
# num_test_x = lm(Patient~. , data = num_test)
```

```{r, categorical}
x = table(categorical_df$Tumor_type)
x = prop.table(x)
x
```

